### ISSUE TITLE
Building with Xcode 14.3

### ISSUE THREAD

**Issue by vkedwardli** [flyinghead/flycast#1078]
Since Xcode 14, deploying to 10.9 is deprecated.

So with 14.3 here comes the new error: `file not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_macosx.a`
(The "Automatic Reference Counting without zeroing weak reference" library)

In case the future [macOS 13](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md) image is using Xcode 14.3 as default, we would have to either
- `xcode-select` Xcode 14.2 before building (preferred)
- Copy `libarclite_macosx.a` from Xcode 14.2 to 14.3 (!?)
- Dropping the support for 10.9 ~ 10.12

**Comment by scribam** [comment]
Is it still an issue?
- We are using Xcode 15.3 in CI since this commit https://github.com/flyinghead/flycast/commit/2d4684a4625ca61c25d8358d2c425dbc533b0095
- Support for 10.9 has been dropped with this commit https://github.com/flyinghead/flycast/commit/4666ea2fdba1a0c225dc99b7cb693962ad494749
- 10.11 is the current minimum but I can see the warnings `The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 14.4.99.` in https://github.com/flyinghead/flycast/actions/runs/9329165696/job/25681275611#step:11:23809

**Comment by vkedwardli** [comment]
You are right, not an issue anymore ~since fanboys are rich and would buy new Macs~
