### ISSUE TITLE
Low-pass filter issue in Skies of Arcadia

### ISSUE THREAD

**Issue by FrankyBuster** [flyinghead/flycast#108]
Audio messes up when playing Ramirez's theme, said issue is more easily replicable by playing it through the PAL debug build which can be obtained on Hidden Palace. https://hiddenpalace.org/Skies_of_Arcadia_(Nov_15,_2000_prototype)

In order to access the debug menu hold the L+R triggers from bootup until it shows up (if done correctly it skips the opening sequence), then go to the sound test, hold B and tap down on the dpad to quickly scroll down through the audio files until you reach M0315 (which is the file for Ramirez's theme), press right on the dpad to change the bank to 3 and press A to play the song, you'll notice it'll glitch up 40 seconds in, and then again at 0:50 and 1:20.

Here's an MP3 of the issue on my end recorded via audacity:
[flycastaudioissue.zip](https://github.com/flyinghead/flycast/files/5141474/flycastaudioissue.zip)

**Comment by flyinghead** [comment]
Thanks for the detailed explanation! With all this it took me less than 5 mins to reproduce the problem.

Interestingly it's not related to the DSP but to the low-pass filter. Having the DSP enabled just amplifies the problem and saturates the audio output completely. This fix isn't perfect but it should help.

**Comment by BlackYoshi485** [comment]
I forgot to mention that due to (probably) the same issue many tracks get static-y, lower gain and play slower, which also produces dc offset errors in the audio, it notably happens at points in Ramirez's theme(such as at 1:20), Ominous Dungeon (M0323, bank 3, through the whole song) and Dungeon of the Dark Rift (M0255, bank 2, most of the song).

**Comment by kode54** [comment]
This is what Highly Theoretical renders it as if you completely disable the low pass filter. I think either the game is broken, or the rip is broken.

https://f.losno.co/Ramirez%27s%20Theme.mp3

**Comment by BlackYoshi485** [comment]
Broken rip, on top of probably incorrect emulation, since the music via sound test and ingame plays perfectly fine on both real hardware and Demul(though with inaccuracies on some tracks).

https://www.youtube.com/watch?v=5gn0Umw8uf0 OST
https://www.youtube.com/watch?v=i98YdIDPkjY my Demul recording
