### ISSUE TITLE
Unsupported Cheat Type

### ISSUE THREAD

**Issue by aknight2015** [flyinghead/flycast#1115]
I'm using the latest version of Flycast on Linux. What format/type does it use when manually adding cheats. I've tried Action Replay, Code Breakers, Game Genie, and RetroArch type. It says "unsupported cheat type" every single time.

**Comment by flyinghead** [comment]
Cheats in Xploder/Code Breaker format are supported. Encrypted cheats (GameShark and possibly others) aren't supported though: the first code should start with a `0`.

For RetroArch, simply load the `.cht` file. Don't enter cheats manually.

**Comment by aknight2015** [comment]
What do you mean the first code should start with zero? Like, all zeroes across the board, and then the rest of the code? Or the first digit for the code should be zero?

**Comment by flyinghead** [comment]
> Like, all zeroes across the board, and then the rest of the code? Or the first digit for the code should be zero?

The latter. For example: `01076418 00000009`

The example you provided isn't supported.

**Comment by aknight2015** [comment]
Alright. Cool. Thanks for helping me figure this out. I was going insane. I'll make sure to remember that in the future.

**Comment by Sumea** [comment]
How in factual heck would someone use codebreaker codes.
like you cannot say "codebreaker is supported" and also say "but if it is in a format that a codebreaker code is shared to you it does not work" and you also add zero anything on figuring out what your cheat needs.
This is REALLY annoying since I try to only add community server connection support that needs one meta and one actual cheat to achieve. And then I find out RA cheats is a mess that has zero documentation and 300% "figure it out here I even burned the documentation for you" energy

**Comment by Smoker1** [comment]
Sorry to Add to a Closed Issue, but I am guessing only Single Line Cheats are supported, and Multi-Line Cheats are not?

Example, for the MK64 Port to DC, there is a Opponents Dont Move Code by luc-ita, and the Code is...
AR-GS (Decrypted)
00C2CAFD 000000B0
00C2D8D5 000000B0
00C2E6AD 000000B0
00C2F485 000000B0
00C3025D 000000B0
00C31035 000000B0
00C31E0D 000000B0

For CB-XP (dont ask, just shows up like this)
00C2CAFD
000000B0
00C2D8D5
000000B0
00C2E6AD
000000B0
00C2F485
000000B0
00C3025D
000000B0
00C31035
000000B0
00C31E0D
000000B0

**Comment by flyinghead** [comment]
Multi-line cheats are supported
