### ISSUE TITLE
L2+ /  R2+ trigger sensitivity with fighting games

### ISSUE THREAD

**Issue by gktonic** [flyinghead/flycast#1188]
MacBook Air M1 - Ventura 13.5.2. DualSense 5 Controller via USB

The problem is that when i use the standard gamepad config for fighting games (i.e. Street Fighter series), the trigger buttons R2 and L2 are usually mapped to 3 kicks and heavy kick. For example, on my PS5 console the triggers send signals instantly (when slightly pressed), but with Flycast i have to push the trigger almost all the way down - ergo moves don't come out properly or not at all. 

Is there any possibility to increase the threshold in a future release? 

Kind regards, Georg

**Comment by vkedwardli** [comment]
Are you mapping your DS5 controller's R2 / L2 to Dreamcast's Buttons or Dreamcast's Trigger (LT2/RT2)?

When mapping to a Dreamcast button, the axis' 100% value is 32767, and a digital button is considered as pressed when the value larger than 16384 (50%)

**Comment by gktonic** [comment]
I see.. but imho it should be at around 5-10% ^^

**Comment by vkedwardli** [comment]
but i guess the problem is DS5 sticks are also axis input **_but with drift_**, setting all axis input to "5% to press a digital button" would cause a drifted stick always returning false positive, so we may need to come up with a cleverer way to separate the half axis and full axis?

I'm not familiar with this problem, please wait for other's input

**Comment by gktonic** [comment]
Thank you very much!! :) I guess that‘d make a lot of fighting game fans very happy.

**Comment by vkedwardli** [comment]
But according to https://github.com/flyinghead/flycast/blob/1377e61d03c14399e4298f1af1a871cc8f00c12a/core/sdl/sdl_gamepad.h#L210-L215

When L2 / R2 is used, even with a minimal press (value = 1),  the overridden value should be: `(1 + 32768) / 2 = 16,384.5`

So may be your macOS/SDL2 failed to recognise the L2/R2 as the `SDL_CONTROLLER_AXIS_TRIGGERLEFT` / `SDL_CONTROLLER_AXIS_TRIGGERRIGHT` ?

Can you try to connect your DS5 with bluetooth instead and verify if the behaviour is the same? (macOS's Game Controller framework supports bluetooth connection only IIRC)

**Comment by gktonic** [comment]
I tried the connection over bluetooth only, but unfortunately the tested game (Capcom vs S K 2 - Naomi Arcade Ver.) still has the R2 Problem. All digital buttons work like they should, but heavy kick only „kicks“ in when the right trigger is at least at pressed 50%. I‘ll
try it again with an old PS4 controller (as soon as i‘ll find it)

**Comment by vkedwardli** [comment]
I was wrong, the range of L2/R2 should be -32768 ~ 32767

**Comment by vkedwardli** [comment]
@gktonic please test if this [macOS build](https://github.com/flyinghead/flycast/suites/15978210053/artifacts/912337291) can solve your problem

(sensitivity reduced from 16384 to 100)

**Comment by gktonic** [comment]
Very, very cool!! :) What you did solved the issue for arcade games (testet with Capcom vs SNK 2 and Street Fighter Zero 3 Upper Arcade). BUT regarding Dreamcast, L and R (which is R1 and R2 on my PS5 controller) now don't work at all anymore. (Neither do L2 or R2 in the config.. but i'm not sure what they mean anyway)

**Comment by vkedwardli** [comment]
Is there any chance you are using the virtual Ascii Stick but not the virtual Sega Controller?
<img width="531" alt="image" src="https://github.com/flyinghead/flycast/assets/602245/5b112210-43a5-4b0f-aff6-971ea3c1ba8e">
Only Sega Controller has Left and Right Trigger

"Left Trigger 2" and "Right Trigger 2" shouldn't have any function in most of the Dreamcast games, since it is used by some special controllers only like racing pedals and fishing rods?

Please try mapping the DS5's L2/R2 to "Left Trigger" / "Right Trigger" or any digital buttons

**Comment by gktonic** [comment]
For some reason, "Twin Stick" was set as Device A. I'm sorry for the confusion..

Now back to "Sega Gamepad", L and R work again (also as digital inputs on triangle and circle i.e.). However, i have to press R2 (R Trigger) fully down to "heavy kick". I testet the inputs with the nice dreamcast input tester - R1 (L Trigger) jumps to 255 immediately (duh), but R2 (R Trigger) has a VERY slow startup from 0 to 255.. means the arcade side is fixed as far i can tell, but the Dreamcast triggers (combined with my PS5 triggers) still don't instantly turn "on"/"255".

**Comment by vkedwardli** [comment]
This is the correct behaviour, since the game decides it’s own threshold when you are using a real Dreamcast Sega Controller with triggers

If you don’t like the delay introduced by the Sega Controller, use ASCII Stick instead, most of the fighting games support it with the ABXY + additional CZ buttons

**Comment by gktonic** [comment]
The Ascii Stick input works flawlessly!! Thank you VERY VERY much for your time!! :)
