### ISSUE TITLE
Love and Berry (SystemSP) Missing triangle on character select screen

### ISSUE THREAD

**Issue by TheCoolPup** [flyinghead/flycast#1200]
Platform / OS / Hardware: Windows 11, Nvidia RTX 3050ti Laptop GPU, AMD Ryzen 5600H @3.3GHz

Github hash: 0fc0dc5

~~These games do boot but from what ive tested, cards do not scan, there is some graphical bugs between screens, and there is some performance issues during some points of the game.~~

![Flycast 9_18_2023 3_31_02 PM](https://github.com/flyinghead/flycast/assets/91135037/e58092d8-7b78-4a46-85f3-fb22123f9add)

**Comment by flyinghead** [comment]
I can see this bogus triangle in the character selection screen but I didn't notice any other bug or glitch.
Performance is fine too. At which point(s) exactly does the performance drops?

Card scanning also works fine here. What happens when you try to scan a card? Double check the Insert Card binding.

**Comment by TheCoolPup** [comment]
so in terms of performance, turns out turning off copy to vram, fixes it and in terms of scanning cards, im used to just copying the barcodes like in demul

**Comment by flyinghead** [comment]
Fixed in the last `dev` build
