### ISSUE TITLE
Langrisser Millennium - Title screen and some parts are not displayed

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1201]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 289f264
ce694ba: Can't reproduce
f4835a8: reproducible

Left image: ce694ba / Right image: f4835a8

![LM_01](https://github.com/flyinghead/flycast/assets/14366233/e2972812-edd4-4e62-80d2-3548de1d1ec8)
![LM_02](https://github.com/flyinghead/flycast/assets/14366233/d2c5fc47-b279-40fd-aca4-c4eb2b3b98b7)

Another problem is that when you select a character, the triangle doesn't disappear and remains on the screen.
(It occurs on both b564b0b and ce694ba)

![LM_03](https://github.com/flyinghead/flycast/assets/14366233/a5cc53b8-8727-47b4-8769-be2b19c84e9c)

Also, is it a known issue that the map screen subwindow is not displayed properly unless the interpreter is enabled?

**Comment by flyinghead** [comment]
The title screen issue should be fixed in the next `dev` build.

The triangles remaining on the screen after selecting a character is due to the depth buffer being written, despite the arrows being invisible (alpha = 0). This is a punch-through polygon with an alpha=0 color. It's possible that, on real hardware, the alpha test of PT polygons is done after shading (in which case the value used for the alpha test is 0). Flycast currently does the test on the texture color only (before shading).
However changing this has other consequences so I'd rather keep it this way for now.

Finally the map screen subwindow seems to have depth issues. Per pixel is needed here. Yet it looks like interpreter and dynarec have different results for the depth. I changed the x64 dynarec to it should now be the same (or at least closer).

**Comment by kihato** [comment]
I have confirmed that it is displayed correctly.
Thanks so much for the fix.

**Comment by flyinghead** [comment]
Reopening for the arrows still being visible after selecting a character.

I verified on real hardware that my conjecture above is correct, and that the flycast implementation is wrong. Working on a fix.

**Comment by flyinghead** [comment]
Should be fixed in the latest `dev` build

**Comment by kihato** [comment]
Thank you again!
