### ISSUE TITLE
Prince of Persia: Arabian Nights - Using save states can corrupt existing files

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1204]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: f75a16f

After starting the game, save the state.
Then go to the first save point and save there.
If you select Load and check the file, you will see that the current time is displayed correctly.

Next, load the save state, go to the first save point again and select save, and you will see that the first saved file is no longer visible.
If you save as is, the elapsed time from the time when the save state was actually recorded will be displayed instead of the current time.

Also, if you use a VM that contains other game files, the files may become corrupted.
![PP_10](https://github.com/flyinghead/flycast/assets/14366233/a740ec6c-74ae-494d-9b20-4b4372647a3d)

**Comment by flyinghead** [comment]
This is expected behavior: save states contain all memory available to the system, which includes VMU data.
This is not clearly documented and can be confusing but there is no easy way around it. The game may be caching some data from the VMU in RAM, and there's a risk of corruption if the vmu data changes unexpectedly (as would happen if loading a state while keeping current vmu data.)

However, this shouldn't cause any corruption since the vmu data is fully restored when loading a state. If you find a scenario that leads to vmu corruption, let me know because it could be a bug.

**Comment by kihato** [comment]
Thanks for your very convincing explanation.
What I did was exactly when loading a state into a VMU brought in from outside.

I'm closing this issue because it doesn't seem possible that the VMU will be damaged due to other factors, even after repeated attempts.
