### ISSUE TITLE
Mr.Driller - Loading text etc. are not displayed when using DX11

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1207]
This issue was confirmed when testing #1067.

Delete data directory and emu.cfg.
Start the game with the default DX11 per-triangle (per-strip).
When the loading text appears, go to the flycast pause menu and exit.
Change to DX11 per-pixel and start the game.

If you first started with per-pixel, now it happens with per-triangle(per-strip).
Also, in Mars Matrix, only the background will be displayed.

I got the same result on another PC (i7-3770 GTX650).

**Comment by flyinghead** [comment]
That's a crazy one and I still don't understand what's going on. It looks like a bug in the directx compiler. It doesn't convert float literals in exactly the same way, leading to small differences.
This is an issue when rounding alpha values before the alpha test for punch-through polygons.

Should be fixed in the next `dev` build.

**Comment by flyinghead** [comment]
By the way, what I said about the dx11 shader cache file was wrong. I was mistaking it with the vulkan pipeline cache, which is proprietary and driver specific.
The dx11 shader cache content is managed by flycast and contains the directx bytecode of all compiled shaders.

**Comment by kihato** [comment]
Oh! It was must have been hard on you. 
Thanks for everything.
