### ISSUE TITLE
Virtua Fighter 3tb "history" video problem

### ISSUE THREAD

**Issue by mfigueirido** [flyinghead/flycast#1218]
Platform / OS / Hardware: 
Windows 10 x64

Github hash: 
cb91ad3ae0c1291485892bf3a9663a2fd303ce83

Hardware: 
AMD Ryzen 2600, Radeon RX 570, 16GB RAM

Game:
Virtua Fighter 3tb (USA) GDI version

The "HISTORY" video does not play correctly when VGA is selected as cable type.

In standalone it will mostly show a black screen but some frames from the video can be seen sometimes. In the libretro core the screen will heavily flash instead. It produced burn-in on my screen so be careful with this!
In both cases the audio playback can be heard just fine.

It was tested with the default settings in both standalone and core. The only thing changed was the cable type to VGA.

**Comment by flyinghead** [comment]
This is due to the game directly writing to the framebuffer in VRAM, which is detected by Flycast and triggers a display of it (black screen). You can see the pixels being written in the upper left corner of the screen:
![image](https://github.com/flyinghead/flycast/assets/16261910/108cb5f1-8489-432b-983a-0306e615afad)

It could be a game bug, some issue with synchronization between CPU and GPU, or some other hack that the game uses.
A workaround is to enable Full Framebuffer Emulation, or to not use VGA.
