### ISSUE TITLE
Manic Panic Ghosts/Pokasuka Ghost (NAOMI) Coin assignments error

### ISSUE THREAD

**Issue by TheCoolPup** [flyinghead/flycast#1237]
Platform / OS / Hardware: Windows 11
2f52492
Hardware: Amd Ryzen 5600H @3.3Ghz Nvidia RTX 3050ti Laptop GPU

the game doesnt boot due to a error with the coin assignments. Happens with Naomi Free Play enabled and disabled

![Flycast 10_11_2023 4_10_25 PM](https://github.com/flyinghead/flycast/assets/91135037/bf291294-0ced-4496-936f-b1781b7007d9)

**Comment by flyinghead** [comment]
This game needs coin assignments sequences to be set a certain way:
![image](https://github.com/flyinghead/flycast/assets/16261910/24f913a2-142b-4458-9009-4c09c42fa234)

Specifically, sequence 2 must be greater or equal than sequence 1, and sequence 4 must be greater or equal than sequence 3.

I will add a default eeprom for this game with correct coin assignments so that no manual config is required.

**Comment by TheCoolPup** [comment]
thanks for the fix, they boot fine now

**Comment by flyinghead** [comment]
should be fixed in the next master build
