### ISSUE TITLE
NBA Hoopz - CDDA playback is incorrect

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1247]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 2a364de
1cadd4e: Can be reproduced
ab791d1: cannot reproduce

If you press the start button on the title screen, you will notice that the audio is out of sync.
This is related to #534.
Guilty Gear X was fixed in #1124, but another game was found.
This time, the problem occurs only when booting with realBIOS.

**Comment by flyinghead** [comment]
This doesn't look related to CDDA. When pressing start the game starts playing CDDA music but the announcer voice is generated by the audio chip. Furthermore I went back to https://github.com/flyinghead/flycast/commit/ab791d1b9c9ae48801a0961d48ee27804fcb0e13 and I can still reproduce the issue.

This looks a lot like #93, which would make sense since NBA Hoopz is the sequel of NBA on NBC.

**Comment by flyinghead** [comment]
Should be fixed in the next master build.

Note that, similarly to #93, you need to use either the TOSEC .gdi dump (`NBA Hoopz v2.000 (2001)(Midway)(US)[!].gdi`) or the Redump .CUE dump (`NBA Hoopz (USA).cue`). The Redump .gdi will not work.

**Comment by kihato** [comment]
The audio during matches is also good.
Thanks for fixing it.
