### ISSUE TITLE
Steam deck: Daytona USA Online mode in the same network not working

### ISSUE THREAD

**Issue by Glost007** [flyinghead/flycast#1552]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware:  Steamdeck SteamOS

Github hash: 

Hardware: 

**_Description of the Issue_**

Hello, I tried to play Daytona USA online on my Steamdeck with someone else in the same network.
I was able to connect to the internet, find a Lobby, create a game and confirm the settings. When I tried to start a Race, the game tried to connect it and after some waiting there was a network error and we were sent back to the lobby.

My Question is: the PSP emulator for the steamdeck needs Sudo permissions to gain access to specific ports to play online, is this necessary for the dreamcast emulator too or is it just because we are playing from the same network?

**Comment by flyinghead** [comment]
Daytona USA cannot be played on the same network since it sends the public IP address in some packets. It also needs port redirection, which is impossible when two players are using the same router.
However these are not privileged ports, so `sudo` shouldn't be needed.
See https://dreamcastlive.net/connection-guide/#dmz for details.

**Comment by Glost007** [comment]
Thank you very much for your answer.
