### ISSUE TITLE
Sega Bass Fishing Challenge (Atomiswave) - Audio cutting out issue

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1564]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: 7d64554

Start the game. After arriving at the first fishing spot, after a while the bird sounds and other audio will be corrupted.

**Comment by kihato** [comment]
I'm not sure what the root cause is, but it seems that the audio glitch occurs when the audio mode is set to mono (default setting).

**Comment by flyinghead** [comment]
While investigating this issue I found a bug with the way Flycast converts stereo audio to mono. It adds left and right channels instead of taking the average, which increases the volume by +6 dB. This can cause saturation or make it worse.
Now even with this bug fixed, or using stereo, the game audio saturates at some point when the general volume is at max setting  (15, which is the default.)

The ambient sounds channel (birds, rain, wind, etc.) is constantly looping but plays 1 to 2 KB of null audio at the end of each loop. The game loads the audio data from the cart, but plays more data than what has been loaded. Due to the codec used (ADPCM), playing null audio makes the channel drift positively, until it completely saturates (32767). This causes other tracks (voice) to saturate as well during mixing.

Still trying to figure out why the game is acting this way.

**Comment by flyinghead** [comment]
mono audio issue fixed on `dev`

**Comment by kihato** [comment]
The sound has stopped cutting out, thanks!
