### ISSUE TITLE
Shaders causing graphical issues with D3D11 renderer

### ISSUE THREAD

**Issue by bslenul** [flyinghead/flycast#1612]
Platform / OS / Hardware: PC / Windows 10 / i5-12400F / RTX 3060 Ti

Github hash: 349083030d85d9e7ae44bddf05090952c6e2bfbc

**_Description of the Issue_**

When enabling shaders while using the D3D11 video driver, it creates graphical issues, see the screenshots below.

Just noticed it while trying to reproduce this issue (I usually use Vulkan and no shaders with Flycast so I never noticed it before): https://www.reddit.com/r/RetroArch/comments/1f01yq8/flycast_core_in_retroarche_will_not_display_game/

Note that once the graphics are "corrupted", disabling shaders doesn't fix it.

**_Debugging Steps Tested_**

Haven't tried much so far besides resetting core options to default and testing an older random commit from early 2022 (830ffd0) which already exhibits the issue.

I also tried other Libretro cores to make sure it was not a RetroArch issue, but shaders look fine in Dolphin, LRPS2 and SwanStation cores when using their D3D11 renderer.

**_Screenshots_**

Screenshots took while using the "crt-geom" CRT preset.

* Sonic Adventure - Vulkan:

  ![image](https://github.com/user-attachments/assets/2a8ff4f4-ff4d-4208-8833-02f3d5eebf33)

* Sonic Adventure - D3D11:

  ![image](https://github.com/user-attachments/assets/9426f234-dcdc-4157-9299-5977cceec8aa)

* Sega Rally 2 - Vulkan:

  ![image](https://github.com/user-attachments/assets/e94104c7-7193-4076-9d0e-0e633c14118d)

* Sega Rally 2 - D3D11:

  ![image](https://github.com/user-attachments/assets/0d9f74de-378e-4cd1-b3f5-91784371d4a9)

**Comment by flyinghead** [comment]
I believe this has been reported before but I have no idea what could cause this.

**Comment by bslenul** [comment]
Ah my bad, I searched for "D3D11" and "shader" but couldn't find any issue about this 🤔 

Also, I have no idea if this is relevant or not but I tried ReShade instead of the internal RetroArch shaders and no issue at all with the few shaders I tested.

**Comment by mfigueirido** [comment]
I always play on Vulkan and shaders work fine. Made a test with D3D11 and got this:

No shaders:
![noshader](https://github.com/user-attachments/assets/c8ef20e7-e645-4c9d-a293-49de61f6e697)

With shaders:
![shader](https://github.com/user-attachments/assets/47a5149c-74a2-4ba2-a056-c538a2bca15e)

If I have to bet on what is happening is that the DirectX shader passes are somehow clashing with Flycast's internal render targets. The shaders are creating their render targets on top of Flycast's render targets and clearing them, that's why some geometry is missing. Maybe those render targets are released but Flycast keeps using them?

**Comment by flyinghead** [comment]
Should be fixed on master

**Comment by bslenul** [comment]
Yup, all good now! Thank you for the fix! ❤️

**Comment by yudhiyou** [comment]
Finally... After years this issue is fixed.
