### ISSUE TITLE
Strange lines on the title screen of the game  Ms. Pac-Man Maze Madness

### ISSUE THREAD

**Issue by melek8014** [flyinghead/flycast#1613]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**
Strange lines on the title screen of the game  Ms. Pac-Man Maze Madness
Platform / OS / Hardware: 
MS Windows 7 64-bit SP1, AMD Athlon X4 880K Quad Core Processor, 12 GB RAM, NVIDIA GeForce 8800 GT
Github hash: 

Hardware: 

**_Description of the Issue_**

Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**
![Bez tytułu](https://github.com/user-attachments/assets/19daa502-0b19-4bdf-9c70-63d7fcd3749d)

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
The two horizontal lines are due to the game using wrong texture coordinates, combined with Repeat mode for the title graphics (in purple). This causes the texture to wrap around and some of the texture bottom pixels are drawn at the top (and vice versa for the bottom textures).

I haven't tested it myself but it looks like it's happening on original hardware too: https://youtu.be/DabyDVblgQ0?si=dzpBVf3ZCVoRUij7&t=27

**Comment by melek8014** [comment]
> The two horizontal lines are due to the game using wrong texture coordinates, combined with Repeat mode for the title graphics (in purple). This causes the texture to wrap around and some of the texture bottom pixels are drawn at the top (and vice versa for the bottom textures).
> 
> I haven't tested it myself but it looks like it's happening on original hardware too

I understand, so it's not the emulator's fault and it's as it should be, thanks for the answer.
