### ISSUE TITLE
Framerate Drop Very Badly on Akira's Stage on Virtua Fighter 4 Final Tuned (Sega Naomi 2)

### ISSUE THREAD

**Issue by yudhiyou** [flyinghead/flycast#1624]
Virtua Fighter 4 Final Tuned(Sega Naomi 2) game is running greatly using Flycast core on Retroarch but there is only 1 stage on that game which cause framerate drop very badly on Akira's stage. I suspect maybe caused by its background animation on it.
Btw I am using PC with Windows 11 OS and playing on Retroarch.

Thank you...

**Comment by flyinghead** [comment]
I believe Akira's stage is Gymnasium, which isn't a very demanding stage. See https://virtuafighter.fandom.com/wiki/Virtua_Fighter_4#Stages for the list of stages.
Some stages are more demanding than others:
- Harbor, Cave and Shrine have water reflections, which requires 2 rendering instead of one (120 renders/s)
- Arena has a large number of animated background characters.

Note that Per-Triangle Transparent Sorting is not recommended for Naomi 2 games. Use Per-Pixel if your GPU supports it, or Per-Strip otherwise.

**Comment by yudhiyou** [comment]
Yes, that's correct. That's gymnasium stage is very laggy and frame drop really badly. Other stages like harbor, cave, shrine, and arena still can be run just fine.
Btw my laptop specs is intel core i3 1115g4.

**Comment by yudhiyou** [comment]
It is running good now. Thank you very much.
