### ISSUE TITLE
Setting dvorak keyboard layout 

### ISSUE THREAD

**Issue by ManofWax** [flyinghead/flycast#1662]
Hello, on my system (Ubuntu) I've configured dvorak keyboard layout, but when I use the dreamcast keyboard the layout inside the game is always US.

Is there a way to change the layout? Specifically setting up dvorak but I think it will help for people that has different layout than US (IE: azerty, qzerty etc.)

**Comment by flyinghead** [comment]
The keyboard layout is detected automatically at start up. However only the existing dreamcast keyboards are supported, and there's no dvorak dreamcast keyboard.

**Comment by ManofWax** [comment]
I see that on settings page the keyboard is detected using "SDL" and there is a page to map keys to Dreamcast controller. Do you think would be possible to add another setting to let people to choose the layout they want to use?

**Comment by ManofWax** [comment]
I took a quick look at the source code,  I think it could be simplier that I tought: I see that in this function dvorak is missing: https://github.com/flyinghead/flycast/blob/master/core/sdl/sdl.cpp#L845 so it goes back to the default US layout. Do you think adding the dvorak detection will solve the problem?

**Comment by flyinghead** [comment]
Some more explanations:
1. Dreamcast keyboard emulation: the physical keyboard layout is detected and the corresponding dreamcast keyboard is emulated. However there was no dvorak dreamcast keyboard layout so even if it was detected it could not be used. (And would default to US.) The `KeyboardLayout` enum (in core/types.h) lists the keyboard layouts defined by Sega's Maple specifications. Dvorak isn't one of them.
2. Using a keyboard as game controller: in this case, the physical keyboard layout is irrelevant since Flycast uses keyboard scan codes for mapping keyboard keys to controller buttons. So the scan code of the Y key on a qwerty keyboard is the same as the Z key on a QWERTZ one (and the F key on a dvorak layout).

**Comment by ManofWax** [comment]
Ok that's make sense. Thank you for the explanation!

Il lun 7 ott 2024, 10:35 flyinghead ***@***.***> ha scritto:
