### ISSUE TITLE
Multiple controllers not working

### ISSUE THREAD

**Issue by jaoxford** [flyinghead/flycast#1702]
Hey,

Love this project. Unfortunately got a weird edge case bug when using multiple controllers for playing Crazy Taxi among other NAOMI arcade titles.

We have a Simagic Wheel, Logitech pedals (using an adapter, this is the important bit, I'll come back to this later), and a shifter.

The wheel, and the shifter are picked up in the list of controllers in flycast, however the pedals (with a Leo Bodnar adapter: https://www.leobodnar.com/shop/index.php?main_page=product_info&cPath=97&products_id=187) are not picked up.

Just curious how flycast gets the list of controllers, is this something from SDL or the [SDL_GameControllerDB](https://github.com/mdqinc/SDL_GameControllerDB)? Would there be a way of updating Flycast to support these pedals, or somehow hack it to work?

It's a weird one, as all the other emulators support the pedals: MAME, Model 2, Supermodel, to name a few.

Any ideas or help would be appreciated

**Comment by flyinghead** [comment]
Flycast does use SDL to handle controllers. It uses the SDL GameController API for supported controllers but can handle other controllers with the Joystick API.
So basically if SDL supports a controller or adapter, Flycast does too.

**Comment by jaoxford** [comment]
Great, still doesn't entirely explain how other emus get it right, and what's missing from Flycast. 

I have found a [similar issue](https://github.com/ValveSoftware/Proton/issues/5126) here regarding the pedal adapter we're using.

**Comment by flyinghead** [comment]
Other emus use other APIs beside SDL.

**Comment by WarpedPolygon** [comment]
@jaoxford XINPUT and DINPUT are the 2 other main API's.

Xinput & Dinput are the more common input APIs. Xinput will pickup any xinput controller, no matter the variant (for 95% of xinput controllers). That's why those other emulators work a bit more seamlessly when using multiple controllers/input types.

SDL uses controller specific profiles from the database. So, if you have an 360 Controller & Xbox ONE controller you'll need to configure for both, separately. You can't configure one and expect it to work with the other despite having the same input system.
This is a double edged sword, you get less indexing issues with SDL especially with lightguns, but you also gotta configure every controller separately as it's own entity.

It would be awesome to get XINPUT & DINPUT in addition of SDL to cover all the bases. But I know that's a big ask.

**Comment by flyinghead** [comment]
SDL uses XInput and DirectInput (and Raw Input and more) under the hood. There's no need for Flycast to reinvent the wheel.

**Comment by jaoxford** [comment]
> SDL uses XInput and DirectInput (and Raw Input and more) under the hood.

If that's the case then why do other emulators pick up the Leo Bodnar Pedals without a hitch, and Flycast doesn't?

**Comment by flyinghead** [comment]
This looks like a SDL issue: https://github.com/libsdl-org/SDL

**Comment by jaoxford** [comment]
I guess I need to try Flycast 2.4 out and see if having a newer SDL fixes things!

Thanks

**Comment by jaoxford** [comment]
Upgrading to Flycast 2.4 fixed this for us. I'm guessing that the later SDL version bundled helped us out here.

Thanks a lot!
