### ISSUE TITLE
Zombie Revenge - Graphic glitches in certain places

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1726]
Platform / OS / Hardware: 
Windows11 / i7-10700F / GTX 1660 SUPER

Flycast version: v2.4-10-gda3cfd9d5
[Zombie Revenge.zip](https://github.com/user-attachments/files/17609979/Zombie.Revenge.zip)

This happens when using Vulkan per-pixel.
But it might be due to the GPU I'm using.

https://github.com/user-attachments/assets/0598e09a-e763-4b45-8cc5-740a78319561

**Comment by flyinghead** [comment]
I can't reproduce this issue here: GTX 1080 with Nvidia drivers 535 (Ubuntu 20.04).

Note that the effect used here is a shadow (you can verify by disabling shadows in the Video settings). This is the only known use of an "inverted shadow", where the shadow cone is lighter than the rest of the scene.

**Comment by kihato** [comment]
I have confirmed that it is a shadow effect.
It seems to be caused by the GPU so I am closing this issue.
Thanks for the detailed explanation and testing!
