### ISSUE TITLE
DCA3 (GTA3 Port for Dreamcast) screen white graphics in-game!

### ISSUE THREAD

**Issue by RetroGamingX** [flyinghead/flycast#1795]
Using the latest development version of Flycast v2.4-126 (Master branch) the graphics are displayed incorrectly, only a white screen is seen. This occurs in all possible APIs and video configurations.

![Desktop 2024-12-30 21-03-26-231](https://github.com/user-attachments/assets/fe383dbd-ac28-4f55-80ac-4efba5245571)
![Desktop 2024-12-30 21-04-07-741](https://github.com/user-attachments/assets/760833ab-9d42-4538-9105-e97bb4a9a2d7)

**Comment by flyinghead** [comment]
Supporting this port as it is isn't planned.
You should ask them to release an emulator-friendly version.

**Comment by RetroGamingX** [comment]
I understand that Flycast is not meant to be accurate, but the goal should still be to make the emulator as close to real hardware as possible, and if it can't emulate this homebrew leaves a lot to be desired to be honest... anyway the problem is related to the traces option, when it is disabled the emulator draws some layers. Don't take this as a complaint, the idea is that the emulator improves over time and doesn't make the same mistake that PCSX2 did years ago; that it works well only in certain games or in the most popular ones.

**Comment by flyinghead** [comment]
Flycast is meant to be as accurate as possible. The only limit being that it's playable on available hardware.
This goes well beyond the limits and would have a significant impact on performance for all games on all platforms.

On the other hand, it's just a few lines of code to change in this inferior port to make it compatible with all emulators.

Or just use a PS2 emulator :stuck_out_tongue:

**Comment by raddad772** [comment]
It's a game that runs fine on real hardware. 

This doesn't affect emu performance for any other games. Even if it were true, since other games DO NOT USE the functionality and thus WOULD NOT BE SLOWED by it, it could easily be added in as interpreter-only which wouldn't affect performance on anything since everyone uses JIT.

Heck, if you're so worried about performance, but want to support it in JIT, make support for it a checkbox in options and only issue modified form of instruction in that case. This is not rocket science. Or add auto-detect.

Calling this awesome piece of history and homebrew "inferior" and refusing to support it isn't a great look

**Comment by wheremyfoodat** [comment]
"Inferior" indeed doesn't sound particularly respectful or like it would be said in good faith,  nor should it be desirable for homebrew to make changes that would potentially make performance worse on real hardware in order to support emulators.

**Comment by flyinghead** [comment]
You apparently know a lot more than me so please contribute to this project.
Waiting for your PR.

**Comment by allkern** [comment]
Do whatever you want with your project. Not supporting a silly cache TA overlay and downplaying the great work of talented developers just because of some irrelevant drama is a terrible look.
