### ISSUE TITLE
Resident Evil: Code Veronica Widescreen Hack

### ISSUE THREAD

**Issue by mohsinous** [flyinghead/flycast#18]
| Platform | Branch | Hash | CIDL |
| Windows 10-x64 | master | 732e685 | Downloaded from build site |

Description of the Issue

widescreen hack is glitchy.
that black transparent layer must not be there.
i tested 90 minutes and it was ok (there was not black transparent layer).

Screenshots

![Flycast git_mmu (built Sep 15 2019@16_35_58) 9_15_2019 9_38_37 PM](https://user-images.githubusercontent.com/32609205/64925209-63f44d80-d802-11e9-8624-8f8a347d0352.png)

- [X] Place an X in the box to confirm you have filled in this form

**Comment by flyinghead** [comment]
The Widescreen Hack, as the name implies, is a hack. This option shows parts of the screen that would normally not be visible.

So it really depends on the game, and sometimes on the scene within a game. There's not much I can do besides hiding.

**Comment by mohsinous** [comment]
thanks again

**Comment by flyinghead** [comment]
I added a new option in the latest build that will activate widescreen cheats/hacks for some supported games and Resident Evil: Code Veronica is one of them.
Enable the "Widescreen Game Cheats" option in the Video section before starting a game.

![re-code-vero-wide](https://user-images.githubusercontent.com/16261910/65584811-c4f9ef00-df81-11e9-845e-a1d4d3c07c43.png)

**Comment by mohsinous** [comment]
![Flycast git_mmu (built Sep 26 2019@07_22_25) 9_26_2019 2_34_29 PM](https://user-images.githubusercontent.com/32609205/65683899-52653e00-e06b-11e9-82ab-55ca0dce3bae.png)
Without any hack ...
![Flycast git_mmu (built Sep 26 2019@07_22_25) 9_26_2019 2_36_09 PM](https://user-images.githubusercontent.com/32609205/65683947-63ae4a80-e06b-11e9-84fe-ff0aa01f3bc7.png)
With Widescreen Hack ...
![Flycast git_mmu (built Sep 26 2019@07_22_25) 9_26_2019 2_37_24 PM](https://user-images.githubusercontent.com/32609205/65684014-80e31900-e06b-11e9-97ee-a2c852a8a9fc.png)
With Widescreen Game Cheats ...
@flyinghead Thank you ... You are Genius

**Comment by mohsinous** [comment]
@flyinghead i know i my requests are so much, but as you see in the second picture, there is a Dark Transparent Layer (DTL) over the screen and in the third picture you extend that DTL!! is there any way to remove DTL instaed of extend it to the whole screen??

**Comment by flyinghead** [comment]
These game cheats haven't been found by me. I just included them in the emulator for convenience.

So there are other cheats doing all kinds of things, including crashing the game ;) I'll think of a generic cheat interface for the future.

**Comment by mohsinous** [comment]
thanks man. look forward to it

**Comment by dezraj** [comment]
> I added a new option in the latest build that will activate widescreen cheats/hacks for some supported games and Resident Evil: Code Veronica is one of them. Enable the "Widescreen Game Cheats" option in the Video section before starting a game.
> 
> ![re-code-vero-wide](https://user-images.githubusercontent.com/16261910/65584811-c4f9ef00-df81-11e9-845e-a1d4d3c07c43.png)

Hello! I'm experiencing this issue as of latest build. I've tried enabling both widescreen options in the settings but could not remove the "dark transparent layer". Has it really been fixed?

I'm using the standalone emulator, Windows version.

Thank you so much for your time and work.

**Comment by Hisham735** [comment]
Why this isn't fixed on Flycast android

**Comment by Nickodemus27** [comment]
Can you do this fix on "BioHazard Code: Veronica Kanzenban" too

**Comment by dezraj** [comment]
> Can you do this fix on "BioHazard Code: Veronica Kanzenban" too ?

So that's why I'm still experiencing this issue here even though it was said to be fixed in this report... I always use the Kanzenban Edition!

I really second your request to extend this fix to the Kanzenban (Complete) Edition, especially because there is a hacked version of this game which replaces the Japanese texts with English ones, and then we have the perfect version to play in the Dreamcast.

**Comment by keefged4** [comment]
Sorry to Necro this, I've been messing around using cheat engine to try and find the widescreen code for this version but I cant quite get there. I'm not really experienced but have managed to find the zoom value - 2C344AB0, and what seems to be the horizontal camera panning value - 2C344AB8 and Vertical - 2C344ABC.  Problem is, the vertical and horizontal values move the camera instead of streching the image if that makes sense. I have found a semi - workaround though, I found the value to disable the "overlay" screen effect which makes the widescreen hack in retroarch Flycast a bit more bareable - 2C275400 + 2C275418. You can disable it completely by changing the value to 0 to both addresses. To use this in retroarch use addresses 36131840 (02275400) and  36131864 (02275418) and set the value to 0 for both of them. If anyone more experienced could find the vertical strech value we'd then be able to get a proper widescreen code though.

**Comment by dezraj** [comment]
Thank you for your efforts @keefged4 . I wish I could help on that. Hopefully someone more skilled will eventually do it and then we will have the perfect CV Complete version adapted for modern screens in Flycast.

**Comment by keefged4** [comment]
Apologies, disregard the last post about removing the overlay, it only seems to remove the effect on the first prision scene, later scenes like the milatary training complex still show the overlay which is annoying.

**Comment by keefged4** [comment]
GOOD NEWS. I have found the code for the Kanzeban English translation rom. Tested and working fine:

Raw Hex :
2C344AB0 - 43F00000 ZOOM
2C344AE4 - 3FA00000 VERTICAL STRETCH

To use this as a cheat code e.g. codebreaker or gameshark input the following:

02C344AB0
43F00000
2C344AE4
3FA00000

For Retroarch:

Address -  36981424, Value 1139802112
Address - 36981476, Value 1067450368

The vertical strech looks good to me with a slight zoom out which should match 16:9 - As metioned I'm no expert at this though, so if anyone has any suggestions for improvement or thinks this looks off, please let me know. Enjoy :)

**Comment by dezraj** [comment]
Great work, @keefged4 ! Now how do I use this in the stand-alone Flycast emulator? Does it have to be implemented in the code? If so, tell me and then I can create a new feature request to get this added to the program because I think the author doesn't check this issue report any more. But I guess you should do it since you are the creator and then you may receive some suggestions to improve it and be notified via e-mail.

Thank you so much for your work. Nothing better than community work in emulation. 🙏

**PS:** does your code work in the official Japanese Complete edition of the game?

**Comment by keefged4** [comment]
Okay so a bit of bad news again, These codes introduce a lot of clipping issues not present in the hex edited iso, so for the time being I'd advise against using these codes for the time being. Not sure how the stand-alone emu works, I'd assume you would be able to try the codes the same way you would impliment gameshark/cpdebeaker though. It's not quite ready yet until the clipping issues are sorted out though.

**Comment by keefged4** [comment]
Okay sorry for all the double posts, I've revised the code to try and reduce the clipping - 

Raw Hex :
2C344AB0 - 43F00000 ZOOM
2C344AE4 - 3FB00000 VERTICAL STRETCH

To use this as a cheat code e.g. codebreaker or gameshark input the following:

02C344AB0
43F00000
2C344AE4
3FB00000

For Retroarch:

Address - 36981424, Value 1139802112
Address - 36981476, Value 1068498944

Seems to work a bit better, but there is still some clipping occuring. Nowhere near as bad this time. 

[Resident Evil - Code Veronica X (English)(Disc 1)(Clone GDEMU Item Bug Fix).txt](https://github.com/flyinghead/flycast/files/10421467/Resident.Evil.-.Code.Veronica.X.English.Disc.1.Clone.GDEMU.Item.Bug.Fix.txt)

I'll try and have a look at flycast standalone to see if I can get it working there.

**Comment by dezraj** [comment]
Hello @keefged4 . You mentioned there is an hex edited ISO of the game without any issues. Is it the one largely available out there? We can't post links here, but I think I have the one which is not "GDEmu patched". Will your code work there either?

Thank you again for your work.

**Comment by keefged4** [comment]
No worries, I haven't used or downloaded a pre-patched widescreen gdi so not sure if you'll be able to find it, I hex patched the English translation gdi using the following:

Resident Evil - Code Veronica
Note: This patch works fine for the
VGA-patched PAL-Versions and
Code Veronica X translated.
PAL
USA
Find
C8A60200 A245963F
Replace
C8A60200 7368613F

You need to hex edit either the track03.bin file with the above or extract the GDI and edit 1ST_READ.bin file with the above.

Not sure if this will work on the standard JP one though. What is the exact name of the GDI/Image you are using and I'll try it?

**Comment by dezraj** [comment]
Hello again! Thank you for your fast reply. The gdi file is named as:
Resident Evil - Code Veronica X v1.000 (2000)(Capcom)(NTSC)(US)(Disc 1 of 2)[!].gdi

The version I'm using here is easily available on line. If I google "code veronica english patched" it's one of the first results here. You also find the GDEmu bug fix version in the same site, but since I don't use GDEmu, I went with the normal version to avoid incompatibility with emulators.

I'm still curious on why the wide-screen patch works fine if you apply directly to the game file image but not as a cheat used by the emulator programs. Perhaps stand-alone Flaycast will have it working correctly as a wide-screen cheat?

Anyway, thank you so much again for working on this feature.

**Comment by keefged4** [comment]
The GDI you are using seems to be the US version, I cant see any results for the exact filename you have given me which is strange. The Kanzeban version is a hack of the JP version and was never released officially, so I'm not sure where you have found the US version of X, it doesn't exist. The Item bug fix should work fine on emulators however - Its the one that is required for retroachievements (Hence why I am on the hunt for the widescreen code/patch in the first place haha!) I'd reccomend using that instead. The code I've found is based on that GDI so I doubt it would work on the US version you have as there is a lot going on in the patched Kanzeban version, its not a straight forward translation by the looks of it.

I'll need to have another look at the codes i've found to see if there is a better solution for the clipping, The Hex edit is clearly different from what I've found.

**Comment by keefged4** [comment]
FINAL UPDATE.

After many hours of trying I have found the correct code which matches the hex edit, no clipping as far as I can see, this code directly affects the horizontal axis without any zoom involved, which I reckon the hex edit is doing anyway.

Raw Hex :
2C344AE1 003F6000

To use this as a cheat code e.g. codebreaker or gameshark input the following:

02344AE1
003F6000

For Retroarch:

Address 36981473 - Value 4153344

I'll attach the Retroarch cheat file too, and post this directly to the other RE CVX thread on here.

Enjoy :)

[Resident Evil - Code Veronica X (English)(Disc 1)(Clone GDEMU Item Bug Fix)WIDESCREEN CODE FINAL.txt](https://github.com/flyinghead/flycast/files/10426175/Resident.Evil.-.Code.Veronica.X.English.Disc.1.Clone.GDEMU.Item.Bug.Fix.WIDESCREEN.CODE.FINAL.txt)

**Comment by keefged4** [comment]
@flyinghead @dezraj 

Can confirm the above code works fine on flycast standalone by adding it in as a cheat manually :)

**Comment by dezraj** [comment]
Thank you so much for your achievement, @keefged4 . It was actually faster than I expected. I'm pretty sure the Resident Evil fan mod community will be glad for your work and enjoy it for years from now on.

Now as for the version of the game I'm using here, I'm pretty sure it's the the Kanzenban English patched. The GDI file is named "X" but it's actually the Kanzenban (Complete) patched. The 7zip file is called like this:
[GDI] Resident Evil - Code Veronica X (English)(Disc 1).7z

In the same site there is also the GDEmu version available. I can't tell you the address here, but it's related with "romantic relationships" and "compact discs", if you can get what I mean. 😂

I tried here your code with the Complete Edition version I have (the one without the GDEmu bug fix) and it worked perfectly. I have to load the game, press Tab to show the menu, go to Cheats and then find the file which you posted above in order to activate the cheat. Finally I have to go to Settings -> Video and stretch the picture horizontally until value 134 in order to fill in a 16:9 monitor.

I'm sure that when this be implemented it will be easier to use: just enable "Widescreen game cheats" and hopefully the screen will be stretched automatically (at least this is what I expect).

Anyway, I think you should create a pull request or open a feature request to get this implemented as it seems to be working pretty good as far as we've tested. I'm not sure @flyinghead head will check comments on closed issues, but let's see...

Thank you so much again for your work. 😊

**Comment by BassHero** [comment]
> FINAL UPDATE.
> 
> After many hours of trying I have found the correct code which matches the hex edit, no clipping as far as I can see, this code directly affects the horizontal axis without any zoom involved, which I reckon the hex edit is doing anyway.
> 
> Raw Hex : 2C344AE1 003F6000
> 
> To use this as a cheat code e.g. codebreaker or gameshark input the following:
> 
> 02344AE1 003F6000
> 
> For Retroarch:
> 
> Address 36981473 - Value 4153344
> 
> I'll attach the Retroarch cheat file too, and post this directly to the other RE CVX thread on here.
> 
> Enjoy :)
> 
> [Resident Evil - Code Veronica X (English)(Disc 1)(Clone GDEMU Item Bug Fix)WIDESCREEN CODE FINAL.txt](https://github.com/flyinghead/flycast/files/10426175/Resident.Evil.-.Code.Veronica.X.English.Disc.1.Clone.GDEMU.Item.Bug.Fix.WIDESCREEN.CODE.FINAL.txt)

@keefged4 , playing the game without the dark layer would be perfect, but Flycast don't load your cheat file, the terminal shows this error at third line bellow:

00:10:451 cheats.cpp:498 N[COMMON]: Applying widescreen hack to game T1204N
00:10:451 emulator.cpp:54 N[BOOT]: Game ID is [T1204N]
**01:34:300 cheats.cpp:394 W[COMMON]: Invalid address 2344ae1**  

Looking for this line in flycast source code, I found this:

382 to 395 lines:

	int count = cfg.get_int("", "cheats", 0);
	cheats.clear();
	for (int i = 0; count == 0 || i < count; i++)
	{
		std::string prefix = "cheat" + std::to_string(i) + "_";
		Cheat cheat{};
		cheat.description = cfg.get("", prefix + "desc", "Cheat " + std::to_string(i + 1));
		cheat.address = cfg.get_int("", prefix + "address", -1);
		if (count == 0 && cheat.address == (u32)-1)
			break;
		if (cheat.address >= RAM_SIZE)
		{
			WARN_LOG(COMMON, "Invalid address %x", cheat.address);
			continue;

**Comment by flyinghead** [comment]
The retroarch .cht file is incorrect: address should be 3427041 instead of 36981473.
However this widescreen cheat is integrated in Flycast (Widescreen Hack) so the .cht file is not needed.

**Comment by BassHero** [comment]
@flyinghead, thanks for answering me. Actually I'm trying to play the game disabling the dark layer, I thought that cht file did it too. 

@keefged4 said "I have found a semi - workaround though, I found the value to disable the "overlay" screen effect which makes the widescreen hack in retroarch Flycast a bit more bareable - 2C275400 + 2C275418. You can disable it completely by changing the value to 0 to both addresses."

However, I could not create a cheat to disable dark overlay from these information. @flyinghead Could you show me how do It?

**Comment by keefged4** [comment]
@BassHero The overlay code I found only applies to the first area and does not disable it from the majority of the rest of the game I'm afraid. You are much better off just using the widescreen code I found, which is included within the flycast widescreen hack anyway. Just enable "Widescreen Cheats" within the retroarch core options, or enable it within Flycast standalone.
