### ISSUE TITLE
Jet Set Radio Custom Graffiti not appearing

### ISSUE THREAD

**Issue by Foxlum** [flyinghead/flycast#232]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Android 11 Pixel 4a 5G

Github hash: 
Hardware: Snapdragon 765G Adreno 620

**_Description of the Issue_**
Custom Graffiti not appearing anywhere except during creation.
**_Debugging Steps Tested_**

  * HLE bios and/or force windows ce on and off
  * Polygon sorting per pixel and strip
  * Both CPU emulation modes, Safe mode, and idle skip.
**_Logs Gathered_**
None
VMU Save 
https://drive.google.com/file/d/1fO9UOh8sy1fz2ORkPbDOPDgB7CotcBIr/view

**_Screenshots_**

Video 
https://drive.google.com/file/d/1fbUTp-2G9QDiFkbMHTZPNTpFDkILIOSH/view

**Comment by flyinghead** [comment]
There are two issues at play here:

1. The graffiti is created by rendering to a texture in VRAM, then saving this memory to the VMU. For this to work, the option `Video > Render to Texture > Copy to VRAM` must be enabled.
2. In Open GL, there is an optimization that copies pixel data to VRAM asynchronously, only waiting for completion when the texture is used in the next frame. Unfortunately the graffiti is not used for rendering before being saved, so the pixel transfer doesnt complete. This works fine in Vulkan since this optimization isn't implemented.

So currently, the workaround to save custom graffiti is to enable `Video > Render to Texture > Copy to VRAM` and use the Vulkan renderer.

Downloading custom graffiti from the web works fine. Only the creation is affected.

**Comment by flyinghead** [comment]
`Video > Render to Texture > Copy to VRAM` is now forced for this game

**Comment by flyinghead** [comment]
Should be fixed in the latest `dev` build
