### ISSUE TITLE
Atomiswave, King of Fighters XI: shorten loading times

### ISSUE THREAD

**Issue by FelipeLema** [flyinghead/flycast#397]
**Is your feature request related to a problem? Please describe.**
Shorten loading times. Namely, in KoF XI, between "end of Order Select" and "selected characters are visible in stage".

**Describe the solution you'd like**
Loading times are close to none. Loading screen ("next stage is") is skipped.

**Describe alternatives you've considered**
I dunno of alternatives. Implementation can be done in any way raging from "speed up emulated hardware", "add virtual RAM with assets" to "hacked rom".

**Additional context**
Measured time currently stands at 10s.

**Comment by flyinghead** [comment]
The game isn't loading much from the cartridge during this period and these DMA transfers are instantaneous from a game standpoint. So there isn't much to gain there.

The best option is to use fast-forward when playing offline. But for online netplay, there is no simple solution since it needs to be automated and it's difficult to detect when to start and stop fast forwarding.

**Comment by FelipeLema** [comment]
does flycast have debugging tools to look for patterns / codes to do such detection? 3rd party tools?

**Comment by flyinghead** [comment]
No, but it logs the host address of the RAM at startup, so a 3rd party tool or debugger could be used.

**Comment by FelipeLema** [comment]
k, thx

leave this open... I'll look into it
