### ISSUE TITLE
A display issue(libretro) upgrading from 1.1 to 1.2

### ISSUE THREAD

**Issue by crashGG** [flyinghead/flycast#454]
OS:    Win10 64bit
Graphics: Intel HD 5300
game:  Ecco the dolphin(USA)
retroarch core version:    1.1-54   vs   1.2-6
retroarch video driver:    gl

picA:  Normal background
![Ecco the Dolphin - Defender of the Future (USA) (En,Fr,De,Es)-211223-205937](https://user-images.githubusercontent.com/80488411/147279553-0e6c824f-87b6-4a17-90b4-6fadf30dd438.png)

picB:  Broken background
![Ecco the Dolphin - Defender of the Future (USA) (En,Fr,De,Es)-211223-205747](https://user-images.githubusercontent.com/80488411/147279788-c1b262ca-4441-4e99-9272-72d03ee7b08b.png)

This display issue occurs when upgrading retroarch core from 1.1-54 to 1.2-6 under the same settings。finally, I found that when "PowerVR Post-processing Filter" is enabled, The screen becomes normal like picA.But with my intel HD Graphics, after the "PowerVR Post-processing Filter" is  enabled, the game drops frames and cannot run at full speed. So usually this option is turned off, which is also the default value.

In addition, standalone flycast from 1.1 to 1.2 under the same settings, without this display problem. The screen is normal as picA.
Did something special happen to the retroarch core 1.2 version?

**Comment by PoloniumRain** [comment]
Same here, it's happening with **many** games though, not just Ecco.

This problems occurs when using the OpenGL or GLcore video drivers within RetroArch in combination with the 'Per-Triangle' or 'Per-Strip' settings for Alpha Sorting. As already mentioned it seems to be a problem with 1.2, because this never happened until recently.

So far i've found 3 workarounds for this issue: 
1. Using the 'Per-Pixel' setting for Alpha Sorting.
2. Using the Vulkan, DX11 or DX12 video drivers in RA (and maybe others but i haven't tested them all).
3. Enabling the PowerVR Post-processing Filter.

Here's _some_ of the games that have this issue:
Crazy Taxi 1/2
Virtua Fighter 3
Skies of Arcadia
Jet Set Radio

I'm using RetroArch 1.9.14, fully updated Win 10, and a RTX 3080 with the latest Nvidia 497.29 drivers.

This is how Crazy Taxi looks:
![image](https://user-images.githubusercontent.com/50634894/147281540-73a00e04-f0e9-4bb8-8703-2d937a75e6ee.png)

**Comment by flyinghead** [comment]
should be fixed in the next core update

**Comment by PoloniumRain** [comment]
@flyinghead That was fast :)

**Comment by PoloniumRain** [comment]
Just tried the new update (1.2-56) and can confirm this has been fixed!
