### ISSUE TITLE
[Adreno] Skies of Arcadia render to texture glitch - Android - Vulkan per-pixel

### ISSUE THREAD

**Issue by 71knight** [flyinghead/flycast#641]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware:  Android 11

Github hash: latest flycast version on retroarch.

Hardware: Snapdragon 855+ / adreno 640

**_Description of the Issue_**
Skies of Arcadia intro transitions/fades have gray bar graphic glitch at bottom of screen.  Also dream sequence with young girl after beating first boss may have graphic corruption or slowdown!  

**_Debugging Steps Tested_**

  * OpenGL transitions are fine but has broken clouds under ship at intro.

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
This looks like yet another Adreno bug. I can reproduce the issue on Adreno 615 and Adreno 630. But it works fine on all other platforms, including Mali-G51 and desktop NVidia.

Adreno drivers just suck and they're getting worse. Each version introduces more bugs and performance regressions.

You're lucky that it somewhat works for you because Vulkan per-pixel doesn't work at all for me on Adreno 660: black screen.

**Comment by 71knight** [comment]
Yes! adreno drivers must suck because even the developer of PPSSPP for Android have a specific selectable option in the settings menu to work around graphic driver bugs for adreno.  Aethersx2 (ps2 emulator for Android) also has a similar fix for adreno buggy drivers called "disable texture barriers".  The developer also complained about adreno drivers.
