### ISSUE TITLE
"Friendly names" for control devices overview

### ISSUE THREAD

**Issue by Ginsonic66** [flyinghead/flycast#664]
It would be very helpful, if you could implement a kind of "friendly name" for each control device (editable in each cfg). 
The combination of VID/PID only (e.g. Keyboard VID_16C0&PID_0488) is not always easy to identify, a custom device name (e.g. Teensy36_BaseController) would be much easier to identify. Thanks a lot!

**Comment by flyinghead** [comment]
The raw api driver now uses actual device names, as they appear in the windows device manager. It might still be confusing since some devices have generic names but it should help. Let me know how it works for you.

**Comment by Ginsonic66** [comment]
Thanks for the fast response and the new version, but... well, no I have five indistinguishable HID-Keyboard and six HID-Mouse entries ;-)
I fear, that is not a really practicable way, but thanks a lot for your efforts!

![95582769-1F5B-4A89-B5CF-D1BEBD087799](https://user-images.githubusercontent.com/83291111/173122302-e1472f37-a1b0-4fba-8030-d9b119859e28.png)

**Comment by Ginsonic66** [comment]
I just tried to set the FriendlyName for the HID device in the registry according to https://www.eightforums.com/threads/tutorial-how-to-change-device-names-in-device-manager.15321/

Now the HID device (friendly) name is shown correctly in Flycast, but I am not the only application user and not everyone will like to modify the Windows registry, so of course it is your decision, how to implement the controller overview in the next versions of Flycast.

**Comment by flyinghead** [comment]
That's an interesting find! But yes, it's not really practical for most users.

More work needed I guess.

**Comment by Ginsonic66** [comment]
FYI: This is the control device list after setting all FriendlyName entries in the registry. Perfect for me, but as mentioned above, not everyones business I fear.

![grafik](https://user-images.githubusercontent.com/83291111/173315638-40bebe8b-63fc-411f-a8bb-ca3495af3254.png)

**Comment by Headrush69** [comment]
Great find Ginsonic66.
When you have multiple HID devices with the same name, you end up with a single mappings file that is changed for all devices rather than per device. Following your suggestion and adding the FriendlyName in regedit fixed everything and Flycast now working flawlessly with my raw input devices.

**Comment by Ginsonic66** [comment]
Thanks Headrush69,
there is some registry work to do, but IMO the overview of multiple devices is highly improved.

**Comment by zaphod4254** [comment]
Yes, having 2 Gun4IR light guns, an I-PAC, a real physical keyboard, and a mouse, it makes it very difficult to determine which is which.  Including device ID in the name would at least allow me to look in Device Manager to figure out which device is which.

Or maybe have some sort of "test" tool where I can press a key/button on a controller and it will tell me which device that is.

**Comment by ProfgLX** [comment]
I am not sure registry "hack" with friendly names will survive unplugging and replugging in different USB ports, so this way might just be temporary. Listing RAW is less friendly of course, but ultimately it worked best for mouse and keyboard devices.

Or changing the way Flycast saves its bindings, instead of only the friendly name (or lack thereof), saving as firendlyname + pid/hid would fix the whole thing :)

**Comment by Ginsonic66** [comment]
You are absolutely right, the FriendlyName method won't survive replugging and I totally agree to you, that a combination of FriendlyName and VID/PID display (maybe switchable) would be the ultimate solution for everyone. It was my first idea (see above) to see both informations combined.

Maybe flyinghead sometimes has some spare time for this, meanwhile many thanks for all, you give to us!

**Comment by zaphod4254** [comment]
Maybe an idea like MAME has with its ctrlr.cfg file.  That is, have a section in the config file where we can specify a friendly name based on the device manager ID info, and the bindings are then tied to that friendly name rather than whatever Windows system names things have.  This also avoids the issue of Windows reassigning ID number when plugging or unplugging devices.

For example, this is my ctrlr.cfg file from MAME for my AimTrak light guns and the analog joystick I have plugged in to USB.

        <input>
            <mapdevice device="PID_1601" controller="GUNCODE_1" />
            <mapdevice device="PID_1602" controller="GUNCODE_2" />
            <mapdevice device="CH FIGHTERSTICK" controller="JOYCODE_1" />2
            <mapdevice device="ATRAK Device #1" controller="JOYCODE_2" />
            <mapdevice device="ATRAK Device #2" controller="JOYCODE_3" />
       </input>

**Comment by zaphod4254** [comment]
This also loosely ties in with an enhancement request I submitted a few weeks ago, to have an option to still combine keyboard input (NOT raw mode) while using raw mode for multiple light gun or mouse input.

https://github.com/flyinghead/flycast/issues/1125

**Comment by flyinghead** [comment]
I now append the device id to the friendly name, which help distinguish the various generic HID devices.

**Comment by Ginsonic66** [comment]
Great, best of both worlds, thanks a lot!

**Comment by zaphod4254** [comment]
Great!
