### ISSUE TITLE
Poor performance in Vulkan Api in Virtua Fighter game 

### ISSUE THREAD

**Issue by Junjikobr** [flyinghead/flycast#705]
Hello I'm having low performance in the game called Virtua Fighter on the Vulkan Api and I'm also having a problem with the audio stuttering on the Vulkan Api. My device is a Samsung A7 2017. And my game is between 20 to 40 fps.

**Comment by flyinghead** [comment]
Are you playing VF3tb or VF4?

How is the performance with Open GL?

What are you settings, video in particular?

**Comment by Junjikobr** [comment]
the game i'm playing is Virtua Fighter 3tb

**Comment by Junjikobr** [comment]
Wait, I'll record a video to show you

**Comment by flyinghead** [comment]
> How is the performance with Open GL?
>
> What are your settings, video in particular?

**Comment by RavenMacDaddy** [comment]
I'm having the opposite situation - great performance with Vulkan, totally tanked with OpenGL.

Great performance with DX11 as well (as expected since NVIDIA has great DX11 performance).

The game in my case is Virtua Fighter 4: Final Tuned (rev B) - NAOMI 2 GD-ROM game.

NVIDIA GTX 1080
Driver 512.95

6x internal res; 2880p/5K
