### ISSUE TITLE
Vibration slider does not work

### ISSUE THREAD

**Issue by RainaAudron** [flyinghead/flycast#707]
Platform / OS / Hardware: Windows 7
Github hash: 76bf5746
Hardware: GTX1060 6GB, 24GB RAM

When using a controller with vibrations selected via purupuru plugin, the vibration slider does not adjust the strength.
Dual Sense has its vibrations too strong, Steam Deck too weak, for example. I tried setting the slider to different amounts but the vibration is the same no matter what the slider is set to.

Thank you for looking into this!

**Comment by flyinghead** [comment]
I don't have a Dual Sense but I tested with a DS3 controller and the slider works fine. I confirmed it by logging the intensity of the rumble sent to the gamepad.

I did find that the perceived rumble intensity didn't change much in the lower range of the scale. Even when set to to 1% I still had significant vibration. I guess the gamepad isn't precise enough for low intensity vibrations?

Using a log scale instead of a linear one could help.

**Comment by RainaAudron** [comment]
Ok, it is the controller then. Dual Sense has a large scale of sensitive vibrations on PS5, but when plugged into a PC, it does them with a lot more strength and less nuance. I just tested Dual Shock 4 and it works a lot better there. 100 value is definitely too strong, though. If you can make the scale on the lower range more sensitive, this would solve the issue, I think. Thank you!

**Comment by flyinghead** [comment]
I pushed a change on the `dev` branch that uses an exponential scale for rumble power, which gives more sensitivity to the lower range of the scale. Can you give it a try? Thanks

**Comment by RainaAudron** [comment]
I just tested it on both PS5 and PS4 controllers. PS5 stops registering under 17, PS4 one´s treshold is under 5, so it looks like PS4 controller has slightly larger range of detectable vibrations on PC. Thank you for the fast fix, much appreciated!
