### ISSUE TITLE
Crazy Taxi 1/2 sound and graphic bug

### ISSUE THREAD

**Issue by elessar38** [flyinghead/flycast#717]
Crazy Taxi 1/2 (Dreamcast) have sound glitch when selecting game mode. For example, choosing the Arcade Rules 10 min mode - during loading, in which we will hear that we have "ten crazy minutes" (here the loading is almost completely skiped and the sound is cut off).

Crazy Taxi 1 (Dreamcast / Naomi) and Crazy Taxi 2 (Dreamcast) also has a shadow problem. The shadow cast by our taxi does not cover any of the white stripes on the road.

**Comment by flyinghead** [comment]
I committed a fix for the shadow issue on the `dev` branch.

Regarding the audio message, I didn't notice it being truncated, or perhaps just the very end but barely noticeable. I assume this is due to the gd-rom loading times being faster than original hardware. Interestingly using HLE BIOS makes the loading time much longer (and the audio not cut off at all as a result)

**Comment by flyinghead** [comment]
Note also that shadows on translucent surfaces are only supported in per-pixel mode.

**Comment by elessar38** [comment]
Overall I have Crazy Taxi 1/2 in chd files, but in this case I tested different versions of gdi (pal / ntsc) with hle bios enabled. The result is a cut sound as there is practically no loading in the flycast version.
On the original hardware, after selecting the 10 minutes mode, the commentator says:
"you have ten crazy minutes"
at my flycast:
"you h ..." -cut
Only 1/4 of the entire sentence can be heard.

As for the graphics, I hope that this issue can be fixed.
