### ISSUE TITLE
No lens flare effect on King of Route 66 and Club Kart

### ISSUE THREAD

**Issue by ledstorm** [flyinghead/flycast#730]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows11x64

Github hash: https://github.com/flyinghead/flycast/releases/tag/v2.0

Hardware: 
Intel i5-4590
16 RAM DDR3
Radeon RX480

No lens flare effect on Naomi 2 games like The king of route 66, Club kart..

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment]
This isn't related to Naomi 2. Lens flare effects for these games use high depth values that are clipped by the near plane.

**Comment by flyinghead** [comment]
Actually the issue is more complex: both games read the output framebuffer in VRAM to determine if the sun is visible in the current frame and how much, then it draws lens flares on the next frame accordingly. By default, Flycast doesn't write the framebuffer into VRAM so lens flares are never drawn.

On the `dev` branch, the new option `Full Framebuffer Emulation` does write the framebuffer to VRAM so the sun is correctly detected and lens flares are visible. Unfortunately this mode is quite intensive and has some inherent limitations (no upscaling or widescreen.)

**Comment by flyinghead** [comment]
These games need `Full Framebuffer Emulation` enabled for lens flare effects
