### ISSUE TITLE
SC1 constant desyncs

### ISSUE THREAD

**Issue by crowspaceboy** [flyinghead/flycast#736]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Win 11

Github hash: 

Hardware: flycast SC1 on fightcade

**_Description of the Issue_**

SC1 desyncs regularly, far more than any other game on fightcade, and continues to do so with multiple players even after both parties delete save states and redownload it from the server. most recent examples below are most extreme examples. in the past these desyncs often clear up after one desync, but for some reason with these particular players they happen consistently after one game, sometimes in the middle of the first game. happens with multiple players at least once, regularly, and it always seems to be -just- sc1. desync causes pause menu to come up briefly, then game eventually crashes.

**_Debugging Steps Tested_**
made sure both players were picking same delay
both players deleted save states and redownloaded from the server
able to play one match before desync
desyncs often happened after game 1, but at least a few times happened -during- game one

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```
https://replay.fightcade.com/flycast/flycast_dc_soulclbr/1662527685460-9735
https://replay.fightcade.com/flycast/flycast_dc_soulclbr/1662444196515-9926
https://replay.fightcade.com/flycast/flycast_dc_soulclbr/1662443378785-9528
https://replay.fightcade.com/flycast/flycast_dc_soulclbr/1662442765038-8012
https://replay.fightcade.com/flycast/flycast_dc_soulclbr/1662442103943-9205
https://replay.fightcade.com/flycast/flycast_dc_soulclbr/1662441896747-4793

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by crowspaceboy** [comment]
https://replay.fightcade.com/flycast/flycast_dc_soulclbr/1662686240418-8328
https://replay.fightcade.com/flycast/flycast_dc_soulclbr/1662686766113-8449

Continues to happen with multiple players at random intervals. Here's two new replays with different players.

**Comment by crowspaceboy** [comment]
Issue persists. Here's some new examples with the most recent version of fightcade/flycast.
https://replay.fightcade.com/flycast/flycast_dc_soulclbr/1668744652412-4029
https://replay.fightcade.com/flycast/flycast_dc_soulclbr/1668744444073-5446
https://replay.fightcade.com/flycast/flycast_dc_soulclbr/1668744226825-7690

**Comment by blueminder** [comment]
While upstream Flycast and Flycast Dojo share much of the same code for netplay, the project you want that actually matches the version with Fightcade is here: https://github.com/blueminder/flycast-dojo

Apart from that, replay links alone are nearly useless for me. What is shown on the Fightcade replay servers are what is broadcast from player 1. What would help me better is having both players save offline replays so that I can compare between them.

It would also help to know the connection details of the players involved, as well as checking the version numbers of Flycast Dojo since some people on Fightcade play on slightly newer version if they go for preview releases. The netcode is largely the same, but if there is different behavior outside of that, it can affect desyncing.

**Comment by vkedwardli** [comment]
Besides the software version(GitHub hash), would be helpful if you can list the hardware used by both players also
