### ISSUE TITLE
Add Resident Evil - Code Veronica X Kanzeban English Patched Widescreen code to the Widescreen cheat repo

### ISSUE THREAD

**Issue by keefged4** [flyinghead/flycast#880]
After many hours of trying I have found the proper 16:9 widescreen code for Resident Evil - Code Veronica X Kanzeban.
This code should work on the GDEMU item bug fix version, as well as the normal english patch too -

02344AE1
003F6000

Let me know if you need anything else :)

**Comment by flyinghead** [comment]
I have a RECVX here with `software_name`: `RESIDENT EVIL CODE VERONICA X`

**Comment by keefged4** [comment]
Yup that's the right one.

**Comment by flyinghead** [comment]
Done

**Comment by keefged4** [comment]
Awesome. Thank you! :)

**Comment by dezraj** [comment]
It would be good if it was tried with the regular Japanese version of the game (the unmodded Kanzenban edition) so the program could identify it and apply the widescreen patch to it too. We may consider that there are also Japanese Flycast users who may be interested in playing the game in their original language as well.

I guess we would just need to check if the original Japanese Complete Edition has a different product name because the widescreen patch should work on it as well since it is the source of the English mod.

**Comment by dezraj** [comment]
Hello @keefged4 and @flyinghead . I've applied the cheat to the unmodded Japanese Kanzenban edition and it seems to be working as good as with the modded version.

Now I don't know how to find the product name for the Japanese Kanzenban. I opened the track01.bin file in a text editor and I see there something like "BIOHAZARD CODE VERONICA PLUS". Is that the game ID?

Thank you in advance for your time.

**Comment by keefged4** [comment]
2 seconds, I'll go grab the GDI and find out

**Comment by keefged4** [comment]
Yup, Its BIOHAZARD CODE VERONICA PLUS. @flyinghead Can you please add the same code for this version too?

**Comment by dezraj** [comment]
I checked the commit details and noticed the serial number T1204N used for this mod is the same for the normal American release, which is not the Kanzenban/Complete/X edition. The one for the Kanzenban release is T1240M, according to redump.org, here: http://redump.org/discs/quicksearch/code-veronica/

But then I checked the track01.bin file for the modded Kanzenban I have here and they changed it to the original American serial (T1204N). So now I was wondering how Flycast would differentiate both the normal American release from the Kanzenban modded one in order to avoid some kind of incompatibility which may exist in the widescreen cheats for the two different releases (I suppose the normal American release already has widescreen cheat codes in the program, no?). @keefged4 and @flyinghead , do you think that issue could happen?

**PS:** I forgot to attach a screenshot of the original Japanese Kanzenban (T1240M) working with the cheat:
![image](https://user-images.githubusercontent.com/27839354/212759446-399c2f3e-fa22-40e6-a027-dd2a475a22ba.png)

**Comment by flyinghead** [comment]
That's fine: cheats are first selected using the product id, then use the version or software name if needed. There's no widescreen cheat for the regular RECV JP currently but adding the name will avoid targeting it with this cheat.

**Comment by dezraj** [comment]
Thank you for your quick reply.

By the way, currently the box art for the English patched Kanzenban is the same as the official American release. Perhaps it could be updated for something like this:
https://cdromance.com/wp-content/uploads/2019/05/Resident-Evil-Code-Veronica-X-USA-DC-Coverart-Box.png

I don't know if this if the right place to do that however.

Thank you again for your work.

**Comment by flyinghead** [comment]
Flycast relies on its product id to find box art for a game so it won't be able to distinguish between official release and patched Kanzenban. Same for the Japanese versions.
