### ISSUE TITLE
No sound when opening the setting 

### ISSUE THREAD

**Issue by EPIC3477** [flyinghead/flycast#889]
Platform / OS / Hardware: 
Windows 7
Github hash: 

Hardware: 
Intel i5
**_Description of the Issue_**

When I'm playing the game and open the setting and resume, the sound will gone (sorry for bad ENG)

**Comment by flyinghead** [comment]
There is likely an issue with your audio card. The sound is completely stopped when pausing and fully reinitialized when resuming the game.
In your case this re-initialization is failing for some reason. Can you enable Log to File and post your flycast.log file?

Also try using a different audio driver in `Settings > Audio` and reinstall/update your windows audio drivers.

**Comment by KAI-SHMUPER** [comment]
Same issue here with same hardware. games go full speed when pressing menu and then resume midgame. The only way to stopping it is to vsync, but audio still doesn't work (the emulation is probably switched to fast forward automatically)
Tried all video and audio plugin combinations and still the same. 
Playing naomi/atomiswave is impossible right now since you have to configure controls for each game after booting them.

Platform / OS / Hardware:
Windows 7

Hardware:
Intel i5-4440
IGPU HD Intel 4600
*Using the latest revision of all graphic and audio drivers.

All previous flycast builds never had this issue when resuming a game.

**Comment by flyinghead** [comment]
I recently fixed an issue that could affect audio when running in single-threaded mode. Enable multi-threading or get the latest master build.

if that doesn’t help, enable Log to File and post your flycast.log.

**Comment by KAI-SHMUPER** [comment]
Sorry for the late reply, but yeah, disabling multithread solved the issue completely. Thanks.
